[theme]

# Primary accent for interactive elements
primaryColor = '#655DBB'

# Background color for the main content area
backgroundColor = '#ECF2FF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0083B8'

# Color used for almost all text
textColor = '#3E54AC'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"